### ISSUE TITLE
Need knowledge on establishing connection between middle tier and database

### ISSUE THREAD

**Issue by sftwre** [max-elixir/MovieManager#10]
These are important questions that need to answered.
- Can we host a web service on the Fox server and how will an Android app connect to it ?
- Can the web service connect to our Oracle database ?
- Are there any security concerns or firewall we should be aware of  ?

The IT department (manage fox servers) and Dr.Tosun (manages our Oracle database) here in the CS department are the main points of contact for this.

**Comment by Jason-Kha** [comment]
If we are to have any issues with connecting to the database, we should contact the TA instead of Tosun; he stated that he will just relay the message to the TA.
