### ISSUE TITLE
Load Data to Your Database

### ISSUE THREAD

**Issue by sftwre** [max-elixir/MovieManager#2]
Use Oracle SQL*LOADER to populate tables with
your application data. Provide enough data so that complex queries will not always result in
empty answers. For tables that are likely to be involved in multi-table SQL queries, insert
tuples that will actually join.

**Comment by Jason-Kha** [comment]
Quotations take up extra characters. We should probably expand the character limit by a little bit for titles, filmtypes, and genres.

film.txt:
    0, 'Avengers: Endgame', 3.0, 'movie', 'superhero', 300.00
    1, 'Spiderman: Far From Ho', 0.05, 'trailer', 'superhero', 50.00
    2, 'Toy Story 4', 0.05, 'trailer', 'Family', 50.00
    3, 'Hellboy (2019)', 2.0, 'movie', 'action', 200.00
    4, 'Little', 1.5, 'movie', 'comedy', 200.00

Example: film type ('trailer') is 9 characters, but max is 7 based on the sql table
    film.log:
    Record 2: Rejected - Error on table FILM, column FILMTYPE. 
    ORA-12899: value too large for column "ZKI628"."FILM"."FILMTYPE" (actual: 9, maximum: 7)

    Record 3: Rejected - Error on table FILM, column FILMTYPE.
    ORA-12899: value too large for column "ZKI628"."FILM"."FILMTYPE" (actual: 9, maximum: 7)

**Comment by Jason-Kha** [comment]
Mostly working, just need to extend the limit for some char values. ad_schedule does not seem to work, though.

    Record 1: Rejected - Error on table AD_SCHEDULE.
    ORA-02291: integrity constraint (ZKI628.SYS_C0019190) violated - parent key not found

    Record 2: Rejected - Error on table AD_SCHEDULE.
    ORA-02291: integrity constraint (ZKI628.SYS_C0019190) violated - parent key not found

    Record 3: Rejected - Error on table AD_SCHEDULE.
    ORA-02291: integrity constraint (ZKI628.SYS_C0019190) violated - parent key not found

**Comment by Jason-Kha** [comment]
Fixed. Primary key was suppose to be screenId, and ad_schedule.txt did not have the primary keys matched with the screenId in movie_schedule.txt.
